name: Sync Stag to main Without Keeping Author Info

on:
  pull_request:
    branches:
      - stag
    types:
      - closed

jobs:
  sync-clean:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout stag branch
        uses: actions/checkout@v4
        with:
          ref: stag
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy files to main without history
        run: |
          git checkout --orphan temp-main
          git rm -rf .
          git reset --hard origin/stag
          git add .
          git commit -m "Synced stag to main without author history"
          git branch -D main || true
          git branch -m main
          git push -f origin main
