name: Auto Merge Stag to main

on:
  pull_request:
    branches:
      - stag
    types:
      - closed

jobs:
  auto-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Merge stag into main using GitHub API
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/merges \
               -d '{"base":"main","head":"stag"}'
