name: Sync Stag to Master Without Keeping Author Info

on:
  pull_request:
    branches:
      - stag
    types:
      - closed

jobs:
  sync-clean:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout stag branch
        uses: actions/checkout@v4
        with:
          ref: stag
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git Identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"

      - name: Create a fresh commit on master
        run: |
          git checkout --orphan temp-main  # Create a new branch without history
          git reset --hard origin/stag     # Reset the working tree to stag
          git add .                         # Stage all files
          git commit -m "Synced stag to master without author history"  # New commit
          git branch -D master || true      # Delete old master branch
          git branch -m master              # Rename temp-main to master
          git push -f origin master         # Force push updated master
