name: Sync Stag to main with Anonymous Commit

on:
  pull_request:
    branches:
      - stag
    types:
      - closed

jobs:
  squash-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git for Anonymous Commit
        run: |
          git config --global user.email "nobody@nowhere.local"
          git config --global user.name "Anonymous"

      - name: Squash and merge stag into main
        run: |
          git fetch origin stag
          git checkout main
          git merge --squash origin/stag  # Squash merge without keeping authorship
          git commit --author="Anonymous <nobody@nowhere.local>" -m "Sync stag to main"
          git push origin main
